services:
  backend:
    build:
      target: dev
    environment:
      - GIN_MODE=debug
    volumes:
      - ./backend:/app
      - /go/pkg/mod
      - ./backend/data:/data

  frontend:
    build:
      target: dev
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
